# Generated by Django 2.2.1 on 2019-05-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('body', models.TextField()),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
