# Generated by Django 2.1.4 on 2018-12-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='feedback',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='result',
            field=models.TextField(null=True),
        ),
    ]
