# Generated by Django 2.2.1 on 2019-05-18 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='body',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='statement',
        ),
    ]
