# Generated by Django 2.1.4 on 2018-12-31 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20181231_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='bode',
            new_name='body',
        ),
    ]
