# Generated by Django 2.2.1 on 2019-05-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('channel', models.TextField()),
                ('text', models.TextField()),
                ('result', models.TextField()),
                ('probability', models.TextField()),
            ],
            options={
                'db_table': 'Record',
            },
        ),
    ]
